# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:

  build:
    working_directory: ~/repo
    environment:
      PGHOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ""
    docker:
      - image: circleci/python:3.8.0-node
      - image: circleci/postgres:11.2-alpine

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "poetry.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v4-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo pip install poetry
            poetry install
            touch .installed

      - save_cache:
          paths:
            - ./.venv
          key: v4-dependencies-{{ checksum "poetry.lock" }}

      - run:
          name: run linters
          command: |
            make lint
            poetry run black src/conduit --check

      - run:
          name: run mypy
          command: |
            make types

      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1

      - run:
          name: Create testing db
          command: |
            sudo apt update
            sudo apt install postgresql-client
            .docker/devdb.sh
            .docker/testdb.sh

      - run:
          name: run tests
          command: |
            make unit

      - run:
          name: run dev app
          command: |
            poetry run pshell etc/development.ini SKIP_CHECK_DB_MIGRATED=1 < .circleci/exit.sh

      - run:
          name: run prod app
          command: |
            DATABASE_URL="postgresql://conduit_dev@localhost/conduit_dev" poetry run pshell etc/production.ini SKIP_CHECK_DB_MIGRATED=1 < .circleci/exit.sh

      - run:
          name: run Postman tests
          command: |
            make devdb
            poetry run pserve etc/development.ini &
            make postman-tests
